spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_spending?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root

logging:
  level:
    root: trace

server:
  port: 7070